name: connects_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  permission_handler: ^12.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.7.1
  retrofit_generator: ^10.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.8.0
  custom_lint_builder: ^0.8.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.10.0


flutter:


  uses-material-design: true
